In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("5. County Stats.csv")

In [5]:
df.head()

,County,Total Population,Total Families,Total Households,Population in Families,Population in Households,Family: Under Eightteen years,House: Under Eightteen years,Family: Eighteen years and over,House: Eighteen years and over,...,Family: Eighteen years and over.1,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian/Other Pacific Islander alone,Some Other Race alone,Two or More Races,Hispanic or Latino (Any race),"White alone, not Hispanic"
0,Anderson County,58458.0,12158.0,17218.0,37417.0,44241.0,11297.0,11471.0,26120.0,32770.0,...,2.15,13660.0,2437.0,92.0,68.0,22.0,735.0,220.0,1534.0,12958.0
1,Andrews County,14786.0,3976.0,5259.0,12922.0,14704.0,4263.0,4312.0,8659.0,10392.0,...,2.18,4315.0,76.0,51.0,31.0,1.0,707.0,78.0,2117.0,2973.0
2,Angelina County,86771.0,22429.0,31090.0,71618.0,83818.0,22794.0,23170.0,48824.0,60648.0,...,2.18,23686.0,4624.0,149.0,243.0,15.0,2045.0,338.0,4108.0,21841.0
3,Aransas County,23158.0,6536.0,9795.0,18281.0,22699.0,4405.0,4519.0,13876.0,18180.0,...,2.12,8826.0,106.0,80.0,154.0,1.0,465.0,163.0,1692.0,7684.0
4,Archer County,9054.0,2597.0,3538.0,7786.0,8998.0,2153.0,2185.0,5633.0,6813.0,...,2.17,3376.0,10.0,25.0,15.0,3.0,83.0,37.0,173.0,3295.0

In [6]:
def cut_county_name(s):
    return s[:-7]

df["County"] = df["County"].map(cut_county_name)

In [8]:
pop_df = df[["County", "Total Population"]].copy()

In [9]:
pop_df.head()

     County  Total Population
0  Anderson           58458.0
1   Andrews           14786.0
2  Angelina           86771.0
3   Aransas           23158.0
4    Archer            9054.0

In [10]:
pop_df.to_csv("County Pop Data.csv")